name: golang-tests
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  golang_tests:
    strategy:
      matrix:
        go: [1.21]
        os: [ubuntu-latest]
    name: tests
    runs-on: ${{ matrix.os }}
    steps:

      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}
          cache: false

      - name: Build
        run: make build

      - name: Test
        run: make test
